baseurl = "https://www.blackcursive.org"
DefaultContentLanguage = "en"
title = "Black Cursive - Tech Blog"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Black Cursive - Tech Blog" # Set a different text for the header on the home page
  subtitle = "Programming Tutorials, Tips and Solutions"
  mainSections = ["post","posts"]
  logo = "img/author.png" # Expecting square dimensions
  favicon = "img/favicon.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true
  enableGitInfo = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
  src = "img/hexagon.jpg"
  # desc = "Hexagon"
  # position: see values of CSS background-position.
  # position = "center top"

[Author]
  name = "Black_Cursive"
  website = "blackcursive.org"
  email = "info@blackcursive.org"
  github = "blackcursive"


[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
